@startuml
ServletContextListener <|-- PostSpringInitListener
QConfigService--> ElasticServerListener
ElasticServerListener -->  PostSpringInitListener
ElasticServerListener --> ElasticIndexServiceImpl
ElasticOrderService <|-- ElasticOrderServiceImpl
ElasticOrderServiceImpl --> ElasticIndexServiceImpl
IndexParamManageServiceImpl --> ElasticOrderServiceImpl
ElasticIndexService <|-- ElasticIndexServiceImpl
IndexParamManageService <|-- IndexParamManageServiceImpl

interface ServletContextListener

class PostSpringInitListener {
contextInitialized()
contextDestroyed()
}

class ElasticServerListener {
QConfigService qConfigService
Map<String, TransportClient> clientMap
+initialized()
+getWriteClient()
+getReadClient()
+getClientMapByClusterNames()
+destroyed()
}
class QConfigService{

}
interface ElasticOrderService
class ElasticOrderServiceImpl{
boolean batchAddOrUpdateElasticOrder()

}
interface ElasticIndexService
class ElasticIndexServiceImpl{
boolean internalUpdateIndex()
boolean doUpdateIndex()
public Pair<Long, List<ElasticRecord>> queryList()

}
interface IndexParamManageService
class IndexParamManageServiceImpl{
public List<IndexParamManageBean> getAllTypeParam()

}

@enduml