@startuml
(*)  --> "直销系统下单QMQ通知或第三订单推送"
--> "解析原始推送数据"
--> "原始数据进入缓存队列,记录订单号\渠道类型\酒店ID"
--> "订单数据适配层,将原始数据转换为EBK能适配的模型"
--> "将可识别模型持久化至数据库和Elasticsearch"
If "" then
--> [同步成功] "发送订单变更事件"
else
--> [同步失败] "订单修复Task,扫描原始数据的缓存队列.进行"
--> "发送订单变更事件"
--> "通过EPush推送平台进行订单变更消息的实时推送"
Endif
--> "酒店处理"
-->(*)
@enduml