@startuml
(*)--> "eb根据酒店id查询酒店信息"
-->if "判断酒店是否开通钟点房业务"
       -->[false] "调用baseinfo接口开通钟点房，同时开通供应商钟点房售卖渠道，并保存操作日志"
       --> "开始创建rp"
   else
-->[true] "开始创建rp"
--> "设置rp上的创建来源=自动创建"
--> "调用price dubbo接口保存rp并保存日志"
--> "并将该rp关联到全日房上，创建产品"
--> "调用price dubbo接口保存产品，及日志"
--> "取出每个sroom价格最靠后的报价，作为报价拷贝源"
--> "根据佣金规则计算出佣金比例"
--> "调用price dubbo接口保存报价及日志"
--> "发送变价消息"
--> (*)
@enduml